name: PR test

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  check-dist:
    name: Check dist/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make changes
        run: |
          echo "Hello, world!" > file.txt
          git add .
      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            await exec.exec('git', [
              'config',
              '--global',
              'user.name',
              `github-actions[bot]`
            ])
            await exec.exec('git', [
              'config',
              '--global',
              'user.email',
              `github-actions[bot]@users.noreply.github.com`
            ])
            await exec.exec('git', ['commit', '-m', 'Syncing QuickSight assets'])
            await exec.exec('git', ['push', 'origin', `HEAD:my-feature-branch`])
            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'my-feature-branch',
              base: 'main',
              title: 'My Pull Request',
              body: 'This PR adds file.txt',
            });
